### ISSUE TITLE
Unable to find autoload.php, bootstrap.php.cache and Kernel.php

### ISSUE THREAD

**Issue by N4IR0** [resquebundle/resque#34]
It seems that the `autoload.php` is not longer existing in the `app` directory in Symfony 3, which is required in `bin/resque`.

Because of that the worker fails with the following exception:
```
PHP Warning:  require(/code/vendor/resquebundle/resque/bin/../../../../app/autoload.php): failed to open stream: No such file or directory in /code/vendor/resquebundle/resque/bin/resque on line 9
PHP Stack trace:
PHP   1. {main}() /code/vendor/resquebundle/resque/bin/resque:0
PHP Fatal error:  require(): Failed opening required '/code/vendor/resquebundle/resque/bin/../../../../app/autoload.php' (include_path='.:/usr/share/php') in /code/vendor/resquebundle/resque/bin/resque on line 9
PHP Stack trace:
PHP   1. {main}() /code/vendor/resquebundle/resque/bin/resque:0
```

Maybe you should use the `autoload.php` in the `vendor` directory.

[EDIT]
Also the `bootstrap.php.cache` is not longer existing if you use Symfony Flex.
Additionally the worker is unable to load the Kernel of Symfony because the kernel is now located under the namespace `App/Kernel`.
Stacktrace of the Kernel issue:
```
PHP Fatal error:  Uncaught Error: Class 'Kernel' not found in /var/www/app/releases/20180225121150/vendor/resquebundle/resque/ContainerAwareJob.php:64
Stack trace:
#0 /var/www/app/releases/20180225121150/vendor/resquebundle/resque/ContainerAwareJob.php(44): ResqueBundle\Resque\ContainerAwareJob->createKernel()
#1 /var/www/app/releases/20180225121150/src/Job/AbstractJob.php(59): ResqueBundle\Resque\ContainerAwareJob->getContainer()
#2 /var/www/app/releases/20180225121150/src/Job/InstanceCreateJob.php(44): App\Job\AbstractJob->run(Array, true)
#3 /var/www/app/releases/20180225121150/vendor/resquebundle/resque/Job.php(57): App\Job\InstanceCreateJob->run(Array)
#4 /var/www/app/releases/20180225121150/vendor/chrisboulton/php-resque/lib/Resque/Job.php(194): ResqueBundle\Resque\Job->perform()
#5 /var/www/app/releases/20180225121150/vendor/chrisboulton/php-resque/lib/Resque/Worker.php(240): Resque_Job->perform()
#6 /var/www/app/releases/201 in /var/www/app/releases/20180225121150/vendor/resquebundle/resque/ContainerAwareJob.php on line 64
```

**Comment by danabrey** [comment]
The autoloader is replaced with the Composer autoloader in #33, which may solve your issue.

**Comment by PhilETaylor** [comment]
This project is currently not compatible (not even tested) with Symfony 4.
